### ISSUE TITLE
Add steps to local development build section

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/rise-time-date#14]
**What should happen**
A designer should be able to find all steps to get the component running in the browser in the readme.

**What currently happens**
Two steps are missing from the local development section:
The need for the script tag in the html:
`<script src="https://widgets.risevision.com/stable/components/rise-time-date/1/rise-time-date.js"></script>`
The need for a helper trigger in the JS:
`RisePlayerConfiguration.Helpers.sendStartEvent( riseTimeDateComponent );`

Thanks!

**Comment by fjvallarino** [comment]
@pcsandford this has been deployed for both `Time and Date` and `Counter`
